//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ifunction.WebChatApi.Contract.Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InnerExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InnerExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebChatApi.Contract.Resources.InnerExceptionMessages", typeof(InnerExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occurred..
        /// </summary>
        internal static string E0 {
            get {
                return ResourceManager.GetString("E0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread [ID: {0}] is aborted manually for [{1}].
        /// </summary>
        internal static string E1 {
            get {
                return ResourceManager.GetString("E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize [{0}]..
        /// </summary>
        internal static string E101 {
            get {
                return ResourceManager.GetString("E101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to do operation at [{0}].
        /// </summary>
        internal static string E102 {
            get {
                return ResourceManager.GetString("E102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data conflict for [{0}] at [{1}].
        /// </summary>
        internal static string E103 {
            get {
                return ResourceManager.GetString("E103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to exchange data with URL: [{0}], caused by Http-Status: {1}({2}).
        /// </summary>
        internal static string E110 {
            get {
                return ResourceManager.GetString("E110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to call remote service: [{0}].
        /// </summary>
        internal static string E120 {
            get {
                return ResourceManager.GetString("E120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object or parameter [{0}] is null or empty..
        /// </summary>
        internal static string E201 {
            get {
                return ResourceManager.GetString("E201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format or value of object [{0}] is invalid..
        /// </summary>
        internal static string E202 {
            get {
                return ResourceManager.GetString("E202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to translate data from type [{0}] to type [{1}].
        /// </summary>
        internal static string E301 {
            get {
                return ResourceManager.GetString("E301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized operation for [{0}] by [{1}].
        /// </summary>
        internal static string E401 {
            get {
                return ResourceManager.GetString("E401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recource for [{0}] at [{1}] is not found or read with error..
        /// </summary>
        internal static string E404 {
            get {
                return ResourceManager.GetString("E404", resourceCulture);
            }
        }
    }
}
